id: taiga
backend:
  executable: mattermost-plugin-taiga
name: Taiga.io
description: Receives webhook events from Taiga.io and makes Mattermost posts for them.
version: '0.0.2'
settings_schema:
  settings:
    - key: Enabled
      display_name: Enable Taiga
      type: bool
      help_text: >
        When true, you can configure Taiga.io webhooks to post message in Mattermost. 
        To help combat phishing attacks, all posts are labelled by a BOT tag.
    - key: UserName
      display_name: User
      type: username
      help_text: >
        Select the username that this integration is attached to.
    - key: Secret
      display_name: Secret
      type: generated
      help_text: >
        This secret is used to authenticate to Mattermost. 
        regenerate_help_text: Regenerates the secret for the webhook URL endpoint. 
        Regenerating the secret invalidates your existing Taiga integrations.
  footer: |
    ここに使い方の説明を書きたい。
    てすと
